---
kind: pipeline
type: docker
name: arm32

platform:
  os: linux
  arch: arm

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: mhzawadi/${DRONE_REPO_NAME}
      auto_tag: false
      tags:
        - v4.9.2-arm
        - latest-arm
      build_args:
        - MH_ARCH=arm32v7/php
        - MH_TAG=7.2-apache-stretch
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password

---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: mhzawadi/${DRONE_REPO_NAME}
      auto_tag: false
      tags:
        - v4.9.2-arm64
        - latest-arm64
      build_args:
        - MH_ARCH=arm64v8/php
        - MH_TAG=7.2-apache-stretch
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password

---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    target: mhzawadi/${DRONE_REPO_NAME}:v4.9.2
    template: mhzawadi/${DRONE_REPO_NAME}:v4.9.2-ARCH
    platforms:
      - linux/arm
      - linux/arm64
depends_on:
  - arm64
  - arm32

---
kind: pipeline
type: docker
name: notification

steps:
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token: 635081347:AAEA56jjuoG3QokgTPb7URrDDJBbBDl1VVc
      to: 595059757

depends_on:
  - manifest
